version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      home-assistant-builder:
        patterns:
          - "home-assistant/builder"

  - package-ecosystem: "docker"
    directory: "/jellyfin-server"
    schedule:
      interval: daily
    commit-message:
      prefix: "fix(deps)"
