# https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please#configuration
handleGHRelease: true
releaseType: simple
extraFiles:
  - path: jellyfin-server/config.yaml
    type: yaml
    jsonpath: $.version
